let selecting=false,dragging=false,startX=0,startY=0,box=null,selectionRect=null,selectionSize=null;
chrome.runtime.onMessage.addListener((m)=>{if(m.type==="START_SELECT") startSelect();else if(m.type==="RECOGNITION_CAPTURED") showBusy(m.rect);});
function startSelect(){if(selecting)return;selecting=true;dragging=false;box=document.createElement("div");box.className="mt-selection";selectionRect=document.createElement("div");selectionRect.className="mt-selection-rect";selectionSize=document.createElement("span");selectionSize.className="mt-selection-size";selectionRect.appendChild(selectionSize);box.appendChild(selectionRect);box.addEventListener("pointerdown",down);box.addEventListener("pointermove",move);box.addEventListener("pointerup",up);box.addEventListener("pointercancel",cancelSelection);document.addEventListener("keydown",onSelectionKeyDown,true);document.body.appendChild(box);}
function stopEvent(e){e.preventDefault();e.stopPropagation();}
function down(e){stopEvent(e);if(e.button!==0)return;dragging=true;startX=e.clientX;startY=e.clientY;box.setPointerCapture(e.pointerId);updateSelection(e.clientX,e.clientY);}
function move(e){if(!selecting||!dragging)return;stopEvent(e);updateSelection(e.clientX,e.clientY);}
function updateSelection(x,y){const left=Math.min(startX,x),top=Math.min(startY,y),width=Math.abs(x-startX),height=Math.abs(y-startY);Object.assign(selectionRect.style,{left:`${left}px`,top:`${top}px`,width:`${width}px`,height:`${height}px`});selectionSize.textContent=`${Math.round(width)} × ${Math.round(height)}`;}
async function up(e){if(!selecting||!dragging)return;stopEvent(e);dragging=false;const rect={left:Math.min(startX,e.clientX),top:Math.min(startY,e.clientY),width:Math.abs(e.clientX-startX),height:Math.abs(e.clientY-startY)};finishSelection();if(rect.width<20||rect.height<20)return;try{const result=await chrome.runtime.sendMessage({type:"RECOGNIZE_REGION",rect,viewport:{width:window.innerWidth,height:window.innerHeight}});removeBusy();renderResults(rect,result)}catch(err){removeBusy();alert("识别失败："+err.message)}}
function onSelectionKeyDown(e){if(e.key==="Escape")cancelSelection(e);}
function cancelSelection(e){if(e)stopEvent(e);finishSelection();}
function finishSelection(){selecting=false;dragging=false;document.removeEventListener("keydown",onSelectionKeyDown,true);if(box){box.removeEventListener("pointerdown",down);box.removeEventListener("pointermove",move);box.removeEventListener("pointerup",up);box.removeEventListener("pointercancel",cancelSelection);box.remove();}box=null;selectionRect=null;selectionSize=null;}
function showBusy(rect){box=document.createElement("div");box.className="mt-overlay";Object.assign(box.style,{left:rect.left+"px",top:rect.top+"px",width:rect.width+"px",height:rect.height+"px"});const content=document.createElement("div"),spinner=document.createElement("span"),label=document.createElement("span");content.className="mt-overlay-loading";content.setAttribute("role","status");content.setAttribute("aria-live","polite");spinner.className="mt-loading-spinner";spinner.setAttribute("aria-hidden","true");label.textContent="正在识别…";content.appendChild(spinner);content.appendChild(label);box.appendChild(content);document.body.appendChild(box);}
function removeBusy(){if(box){box.remove();box=null}}
function renderResults(rect,result){if(!result?.ok)throw new Error(result?.error||"未知错误");const items=result.items||[],text=items.map(x=>{const value=x.translated||x.text;return value?.trim();}).filter(Boolean).join("\n\n");box=document.createElement("div");box.className="mt-overlay";Object.assign(box.style,{left:rect.left+"px",top:rect.top+"px",width:rect.width+"px",height:rect.height+"px"});const panel=box,close=document.createElement("button"),content=document.createElement("div");close.className="mt-overlay-close";close.type="button";close.textContent="×";close.setAttribute("aria-label","关闭识别结果");content.className="mt-overlay-content";content.textContent=text||"未识别到文字";const dismiss=()=>{panel.remove();if(box===panel)box=null;document.removeEventListener("keydown",onKeyDown,true);};const onKeyDown=e=>{if(e.key==="Escape")dismiss();};close.addEventListener("click",dismiss);panel.appendChild(content);panel.appendChild(close);document.body.appendChild(panel);document.addEventListener("keydown",onKeyDown,true);}