"""Generate extension/ocr/vocab.js from the manga-ocr character vocabulary.

The decoder emits ids into a 6144-entry *character-level* Japanese vocabulary
(derived from cl-tohoku/bert-base-japanese-char-v2). Reproducing that mapping is
the whole reason this project cannot use transformers.js in the browser: the
upstream config declares a MeCab-backed BertJapaneseTokenizer, and there is no
MeCab in a browser. We only ever need id -> text, so a flat array is enough.

Special tokens are emitted as empty strings, which makes decoding equivalent to
`tokenizer.decode(ids, skip_special_tokens=True)`.

Usage:
    python tools/build_vocab.py --model-dir SNAPSHOT --out extension/ocr/vocab.js
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model-dir", required=True, help="local manga-ocr snapshot containing vocab.txt")
    parser.add_argument("--out", required=True, help="path of the generated JS module")
    args = parser.parse_args()

    vocab_path = Path(args.model_dir) / "vocab.txt"
    tokens = vocab_path.read_text(encoding="utf-8").splitlines()
    if not tokens:
        raise SystemExit(f"empty vocab: {vocab_path}")

    # Indices 0-4 are [PAD] [UNK] [CLS] [SEP] [MASK]; the next block is <unused*>,
    # plus a few bracketed entries. Everything else is a real character.
    def is_special(token: str) -> bool:
        return token.startswith("<") and token.endswith(">") or token.startswith("[") and token.endswith("]")

    special = sum(1 for token in tokens if is_special(token))
    table = ["" if is_special(token) else token for token in tokens]

    body = json.dumps(table, ensure_ascii=False, separators=(",", ":"))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "// Generated by tools/build_vocab.py from kha-white/manga-ocr-base's vocab.txt.\n"
        "// Do not edit by hand. Special tokens are empty strings so that joining the\n"
        "// looked-up entries is equivalent to skip_special_tokens=True.\n"
        f"export const VOCAB_SIZE = {len(table)};\n"
        f"export const VOCAB = {body};\n",
        encoding="utf-8",
    )
    print(f"vocab entries : {len(table)}")
    print(f"special/blank : {special}")
    print(f"wrote         : {out} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
